# Generated by Django 4.0 on 2024-01-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/account/2024-01-14 16:45:08.332423/'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request', models.IntegerField(default=-1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='account.user')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='account.user')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
