# Generated by Django 4.0 on 2024-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_private_account_alter_user_image_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/account/2024-01-20 12:55:25.182585/'),
        ),
    ]
