# Generated by Django 4.0 on 2024-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/account/2024-02-03 08:11:33.153639/'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
