# Generated by Django 4.0 on 2024-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
