# Generated by Django 4.0 on 2024-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_book_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
