# Generated by Django 4.0 on 2024-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_book_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-data_of_publish',)},
        ),
        migrations.AlterModelOptions(
            name='bookborrower',
            options={'ordering': ('-modified_datetime',)},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/lms/2024-02-03 15:20:59.736376/'),
        ),
    ]
