# Generated by Django 4.0 on 2024-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_book_options_alter_bookborrower_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrower',
            name='amount_fine',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/lms/2024-02-04 18:11:08.419702/'),
        ),
    ]
