# Generated by Django 4.0 on 2024-02-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_bookborrower_amount_fine_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrower',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/lms/2024-02-05 02:05:11.194398/'),
        ),
    ]
